### PR TITLE
grails-plugin-tomcat-8.0.14.jar not found

### PR DESCRIPTION
**Pull request by kensiprell**
When upgrading from tomcat:7.0.54 to tomcat:8.0.14 I got the output below after `grails run-app`. I assume this is a leftover from moving the tomcat8 plugin to tomcat.

```
| Error Tomcat plugin classes JAR grails-plugin-tomcat-8.0.14.jar not found
| Running Grails application
Error: Could not find or load main class org.grails.plugins.tomcat.fork.ForkedTomcatServer
| Error Forked Grails VM exited with error
```

### CODE REVIEW

**Comment by burtbeckwith** [comment]
That's a whole lot of unnecessary commits

**Comment by burtbeckwith** [comment]
Note that Tomcat 7 is in its own branch and master is Tomcat 8

**Comment by kensiprell** [comment]
I forked https://github.com/grails-plugins/grails-tomcat-plugin and created the pull request from there, but it ended up on your old branch. I've been trying to figure out how to get it right. It's a minor change in (https://github.com/grails-plugins/grails-tomcat-plugin/blob/master/scripts/_Events.groovy#L7): tomcat8 to tomcat.

I tired to file a JIRA, but the only version available was 7.0.50.

What should I do?

**Comment by burtbeckwith** [comment]
Use the incorrect version and specify the correct one(s) in the description. I'll update the versions in JIRA and update your issue

**Comment by kensiprell** [comment]
I created a JIRA (https://jira.grails.org/browse/GPTOMCAT-27 https://jira.grails.org/browse/GPTOMCAT-27), but I failed to let you know.

**Pull request closed without merging**
